#define ACTION_DISTANCE 15.0

forward OnPlayerOpenVehicle(playerid, modelid);
forward OnPlayerCloseVehicle(playerid, modelid);
forward OnPlayerStartVehicle(playerid, modelid);
forward OnPlayerStopVehicle(playerid, modelid);
forward OnPlGiveItemToPlayer(playerid, toplayerid, itemid, params[]);
forward OnPlShowItemToPlayer(playerid, toplayerid, itemid, params[]);
forward OnPlayerHospitalBed(playerid);
forward OnPlayerAtmWithdraw(playerid);
forward OnPlayerAtmDeposit(playerid);
forward OnPlayerVehicleLightsOn(playerid, modelid);
forward OnPlayerVehicleLiOff(playerid, modelid);
forward OnPlayerOpenProperty(playerid);
forward OnPlayerCloseProperty(playerid);
forward OnPlayerCarryWeapon(playerid, weaponid);
forward OnPlayerUncarryWeapon(playerid, weaponid);
forward OnPlayerEat(playerid, itemid);
forward OnPlayerDrink(playerid, itemid);